services:
  dashboard:
    build:
      context: ./tumbasna-dashboard
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        DIRECT_URL: ${DIRECT_URL}
    container_name: tumbasna_dashboard
    restart: unless-stopped
    env_file:
      - ./tumbasna-dashboard/.env
    ports:
      - "3000:3000"

  whatsapp-bot:
    build:
      context: ./tumbasna-whatsapp
      dockerfile: Dockerfile
    container_name: tumbasna_whatsapp_bot
    restart: unless-stopped
    env_file:
      - ./tumbasna-whatsapp/.env
    ports:
      - "3002:3002"
    volumes:
      - ./tumbasna-whatsapp/session:/app/session
    environment:
      - NODE_ENV=production
    depends_on:
      - dashboard
